export type SupportedGame = {
    key: string;
    name: string;
    sourceName: string;
    steamAppId: number;
    cover: string;
};

export const supportedGames: SupportedGame[] = [
    { key: "EldenRing", name: "艾尔登法环", sourceName: "ELDEN RING", steamAppId: 1245620, cover: "https://assets-mod.3dmgame.com/static/upload/game/620b6924d8c0d.png" },
    { key: "RimWorld", name: "边缘世界", sourceName: "RimWorld", steamAppId: 294100, cover: "https://assets-mod.3dmgame.com/static/upload/game/19.jpg" },
    { key: "Frostpunk2", name: "冰汽时代 2", sourceName: "Frostpunk 2", steamAppId: 1601580, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202410/MOD6706347b70717.webp@webp" },
    { key: "BaldursGate3", name: "博德之门3", sourceName: "Baldurs Gate 3", steamAppId: 1086940, cover: "https://assets-mod.3dmgame.com/static/upload/game/5f9fc80ea912c.png" },
    { key: "CitiesSkylines2", name: "城市天际线2", sourceName: "Cities Skylines II", steamAppId: 949230, cover: "https://assets-mod.3dmgame.com/static/upload/game/6535dbba96ba3.webp" },
    { key: "WulinSH", name: "大侠立志传", sourceName: "WulinSH", steamAppId: 1948980, cover: "https://assets-mod.3dmgame.com/static/upload/game/641d08aca63ce.webp" },
    { key: "DysonSphereProgram", name: "戴森球计划", sourceName: "Dyson Sphere Program", steamAppId: 1366540, cover: "https://assets-mod.3dmgame.com/static/upload/game/60112fb1bdafa.png" },
    { key: "TheRoadOfJianghu", name: "刀剑江湖路", sourceName: "The road of Jianghu", steamAppId: 2361680, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202409/MOD66ee9421978bf.jpg@webp" },
    { key: "DaoYanJue", name: "道衍诀", sourceName: "DaoYanJue", steamAppId: 1951220, cover: "https://assets-mod.3dmgame.com/static/upload/game/66447d161b2ff.webp" },
    { key: "Hellblade2", name: "地狱之刃2", sourceName: "Senua's Saga Hellblade 2", steamAppId: 2461850, cover: "https://assets-mod.3dmgame.com/static/upload/game/181.jpg" },
    { key: "PlanetZoo", name: "动物园之星", sourceName: "Planet Zoo", steamAppId: 703080, cover: "https://assets-mod.3dmgame.com/static/upload/game/653a085c9ddd7.webp" },
    { key: "GhostOfTsushima", name: "对马岛之魂", sourceName: "Ghost of Tsushima", steamAppId: 2215430, cover: "https://assets-mod.3dmgame.com/static/upload/game/664703cf381cf.webp" },
    { key: "LordsOfTheFallen", name: "堕落之主", sourceName: "Lords of the Fallen", steamAppId: 1501750, cover: "https://assets-mod.3dmgame.com/static/upload/game/664db7b3148f8.webp" },
    { key: "Fallout4", name: "辐射4", sourceName: "Fallout 4", steamAppId: 377160, cover: "https://assets-mod.3dmgame.com/static/upload/game/6b.png" },
    { key: "StateOfDecay2", name: "腐烂国度2", sourceName: "State of Decay 2", steamAppId: 495420, cover: "https://assets-mod.3dmgame.com/static/upload/game/238.png" },
    { key: "GB4", name: "高达创坏者 4", sourceName: "GUNDAM BREAKER 4", steamAppId: 1672500, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202410/MOD670635775ec6c.webp@webp" },
    { key: "GuLong", name: "古龙风云录", sourceName: "GuLong", steamAppId: 2340650, cover: "https://assets-mod.3dmgame.com/static/upload/game/65bef978b5da4.webp" },
    { key: "MonsterHunterWilds", name: "怪物猎人 荒野", sourceName: "Monster Hunter Wilds", steamAppId: 2246340, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202502/MOD67beca9449633.webp@webp" },
    { key: "MonsterHunterRise", name: "怪物猎人: 崛起", sourceName: "MonsterHunterRise", steamAppId: 1446780, cover: "https://assets-mod.3dmgame.com/static/upload/game/61dbdb30cdbce.png" },
    { key: "MonsterHunterWorld", name: "怪物猎人: 世界", sourceName: "Monster Hunter World", steamAppId: 582010, cover: "https://assets-mod.3dmgame.com/static/upload/game/161b.png" },
    { key: "Expedition33", name: "光与影：33号远征队", sourceName: "Clair Obscur Expedition 33", steamAppId: 1903340, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_6809e94cd72e9.jpg" },
    { key: "TaleofImmortal", name: "鬼谷八荒", sourceName: "Tale of Immortal", steamAppId: 1468810, cover: "https://assets-mod.3dmgame.com/static/upload/game/603e05b7aef61.png" },
    { key: "DevilMayCry5", name: "鬼泣5", sourceName: "Devil May Cry 5", steamAppId: 601150, cover: "https://assets-mod.3dmgame.com/static/upload/game/183.jpg" },
    { key: "Hades2", name: "哈迪斯2", sourceName: "Hades2", steamAppId: 1145350, cover: "https://assets-mod.3dmgame.com/static/upload/game/663add9906fe2.webp" },
    { key: "HaiShan", name: "海山：昆仑镜", sourceName: "HaiShan", steamAppId: 2180340, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202407/MOD669638c34fae8.webp@webp" },
    { key: "DarkestDungeon", name: "黑暗地牢", sourceName: "Darkest Dungeon", steamAppId: 262060, cover: "https://assets-mod.3dmgame.com/static/upload/game/88.jpg" },
    { key: "DarkestDungeon2", name: "黑暗地牢2", sourceName: "Darkest Dungeon 2", steamAppId: 1940340, cover: "https://assets-mod.3dmgame.com/static/upload/game/664ef0d003b8a.webp" },
    { key: "BlackWukong", name: "黑神话: 悟空", sourceName: "Black Myth Wukong", steamAppId: 2358720, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202408/MOD66b5c72696594.webp@webp" },
    { key: "Palworld", name: "幻兽帕鲁", sourceName: "Palworld", steamAppId: 1623730, cover: "https://assets-mod.3dmgame.com/static/upload/game/65ae3cdbc7680.webp" },
    { key: "RedDeadRedemption", name: "荒野大镖客", sourceName: "Red Dead Redemption", steamAppId: 2668510, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202410/MOD6721f29b85384.jpg@webp" },
    { key: "RedDead2", name: "荒野大镖客2", sourceName: "Red Dead Redemption 2", steamAppId: 1174180, cover: "https://assets-mod.3dmgame.com/static/upload/game/208.png" },
    { key: "Ace7Game", name: "皇牌空战7", sourceName: "ACE COMBAT 7", steamAppId: 502500, cover: "https://assets-mod.3dmgame.com/static/upload/game/65f174af429dd.webp" },
    { key: "LegendOfMortal", name: "活侠传", sourceName: "Legend Of Mortal", steamAppId: 1859910, cover: "https://assets-mod.3dmgame.com/static/upload/game/667126e01ba80.webp" },
    { key: "HogwartsLegacy", name: "霍格沃茨之遗", sourceName: "Hogwarts Legacy", steamAppId: 990080, cover: "https://assets-mod.3dmgame.com/static/upload/game/63e2f9656f092.webp" },
    { key: "DontStarve", name: "饥荒 & 联机版", sourceName: "Don't Starve Together", steamAppId: 322330, cover: "https://assets-mod.3dmgame.com/static/upload/game/14.jpg" },
    { key: "ContrabandPolice", name: "缉私警察", sourceName: "Contraband Police", steamAppId: 756800, cover: "https://assets-mod.3dmgame.com/static/upload/game/65f1169237040.webp" },
    { key: "Anno117", name: "纪元117：罗马和平", sourceName: "Anno 117 - Pax Romana", steamAppId: 3274580, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_690ab14576ba4.png" },
    { key: "Anno1800", name: "纪元1800", sourceName: "Anno 1800", steamAppId: 916440, cover: "https://assets-mod.3dmgame.com/static/upload/game/189.png" },
    { key: "SILENTHILLf", name: "寂静岭 F", sourceName: "Silent Hill f", steamAppId: 2947440, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_68d35aebce565.png" },
    { key: "Homeworld3", name: "家园3", sourceName: "Homeworld 3", steamAppId: 1840080, cover: "https://assets-mod.3dmgame.com/static/upload/game/6423ab827ad41.webp" },
    { key: "Kenshi", name: "剑士", sourceName: "Kenshi", steamAppId: 233860, cover: "https://assets-mod.3dmgame.com/static/upload/game/186.png" },
    { key: "StellarBlade", name: "剑星", sourceName: "Stellar Blade", steamAppId: 3489700, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_683eb2f1cdd6b.jpg" },
    { key: "StreetFighter6", name: "街头霸王6", sourceName: "Street Fighter 6", steamAppId: 1364780, cover: "https://assets-mod.3dmgame.com/static/upload/game/64ad1276b1fca.png" },
    { key: "KerbalSpaceProgram", name: "坎巴拉太空计划", sourceName: "Kerbal Space Program", steamAppId: 220200, cover: "https://assets-mod.3dmgame.com/static/upload/game/62.jpg" },
    { key: "WatchDogs2", name: "看门狗2", sourceName: "Watch Dogs 2", steamAppId: 447040, cover: "https://assets-mod.3dmgame.com/static/upload/game/176.jpg" },
    { key: "HollowKnight", name: "空洞骑士", sourceName: "Hollow Knight", steamAppId: 367520, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_68ef7e4cbc70c.png" },
    { key: "Silksong", name: "空洞骑士：丝之歌", sourceName: "Hollow Knight Silksong", steamAppId: 1030300, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_68baa8da077d0.jpg" },
    { key: "GrimDawn", name: "恐怖黎明", sourceName: "Grim Dawn", steamAppId: 219990, cover: "https://assets-mod.3dmgame.com/static/upload/game/80.jpg" },
    { key: "TheHunterCotW", name: "猎人: 荒野的召唤", sourceName: "The Hunter CotW", steamAppId: 518790, cover: "https://assets-mod.3dmgame.com/static/upload/game/64e2df9a8310c.webp" },
    { key: "DragonCliff", name: "龙崖", sourceName: "Dragon Cliff", steamAppId: 758190, cover: "https://assets-mod.3dmgame.com/static/upload/game/235.png" },
    { key: "DragonsDogma2", name: "龙之信条2", sourceName: "Dragons Dogma 2", steamAppId: 2054970, cover: "https://assets-mod.3dmgame.com/static/upload/game/65f8f21471754.webp" },
    { key: "DBFighterZ", name: "龙珠战士Z", sourceName: "DRAGON BALL FighterZ", steamAppId: 678950, cover: "https://assets-mod.3dmgame.com/static/upload/game/157.jpg" },
    { key: "TheLongDark", name: "漫漫长夜", sourceName: "The Long Dark", steamAppId: 305620, cover: "https://assets-mod.3dmgame.com/static/upload/game/65.png" },
    { key: "AmericanTruckSimulator", name: "美国卡车模拟器", sourceName: "American Truck Simulator", steamAppId: 270880, cover: "https://assets-mod.3dmgame.com/static/upload/game/52.jpg" },
    { key: "MiChangSheng", name: "觅长生", sourceName: "MiChangSheng", steamAppId: 1189490, cover: "https://assets-mod.3dmgame.com/static/upload/game/60d93f98c7462.png" },
    { key: "CultOfTheLamb", name: "咩咩启示录", sourceName: "Cult Of The Lamb", steamAppId: 1313140, cover: "https://assets-mod.3dmgame.com/static/upload/game/65f2c99bb3e08.webp" },
    { key: "WuchangFallenFeathers", name: "明末：渊虚之羽", sourceName: "Wuchang Fallen Feathers", steamAppId: 2277560, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_68818e5553d86.jpg" },
    { key: "RedAlert2", name: "命令与征服：红色警戒 2 及尤里的复仇", sourceName: "Command & Conquer Red Alert 2 and Yuri's Revenge", steamAppId: 2229850, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_6a2242d3d562a.png" },
    { key: "FS22", name: "模拟农场 22", sourceName: "Farming Simulator 22", steamAppId: 1248130, cover: "https://assets-mod.3dmgame.com/static/upload/game/61a9e018c601c.png" },
    { key: "TheSims4", name: "模拟人生4", sourceName: "The Sims 4", steamAppId: 1222670, cover: "https://assets-mod.3dmgame.com/static/upload/game/8a.jpg" },
    { key: "TheCallistoProtocol", name: "木卫四协议", sourceName: "The Callisto Protocol", steamAppId: 1544020, cover: "https://assets-mod.3dmgame.com/static/upload/game/6605404b51bc3.webp" },
    { key: "WarmSnow", name: "暖雪", sourceName: "WarmSnow", steamAppId: 1296830, cover: "https://assets-mod.3dmgame.com/static/upload/game/61eb6d1e3f646.png" },
    { key: "EuroTruckSimulator2", name: "欧洲卡车模拟2", sourceName: "Euro Truck Simulator 2", steamAppId: 227300, cover: "https://assets-mod.3dmgame.com/static/upload/game/15.jpg" },
    { key: "LiesofP", name: "匹诺曹的谎言", sourceName: "Lies of P", steamAppId: 1627720, cover: "https://assets-mod.3dmgame.com/static/upload/game/65127b4a5041a.webp" },
    { key: "SparkingZERO", name: "七龙珠 电光炸裂！ZERO", sourceName: "SparkingZERO", steamAppId: 1790600, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202412/MOD675a58a521b54.png@webp" },
    { key: "7DaystoDie", name: "七日杀", sourceName: "7 Days to Die", steamAppId: 251570, cover: "https://assets-mod.3dmgame.com/static/upload/game/40.jpg" },
    { key: "MountBlade2", name: "骑马与砍杀2: 领主", sourceName: "MountBlade2", steamAppId: 261550, cover: "https://assets-mod.3dmgame.com/static/upload/game/225.png" },
    { key: "Stalker2", name: "潜行者2：切尔诺贝利之心", sourceName: "Stalker2", steamAppId: 1643320, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202412/MOD675955ed444f0.png@webp" },
    { key: "L4D2", name: "求生之路2", sourceName: "Left 4 Dead 2", steamAppId: 550, cover: "https://assets-mod.3dmgame.com/static/upload/game/12.jpg" },
    { key: "TotalWarTK", name: "全面战争: 三国", sourceName: "Total War THREE KINGDOMS", steamAppId: 779340, cover: "https://assets-mod.3dmgame.com/static/upload/game/193.png" },
    { key: "TWW3", name: "全面战争: 战锤3", sourceName: "Total War WARHAMMER III", steamAppId: 1142710, cover: "https://assets-mod.3dmgame.com/static/upload/game/61dbfe86987ba.png" },
    { key: "Stellaris", name: "群星", sourceName: "Stellaris", steamAppId: 281990, cover: "https://assets-mod.3dmgame.com/static/upload/game/21.jpg" },
    { key: "Humankind", name: "人类", sourceName: "Humankind", steamAppId: 1124300, cover: "https://assets-mod.3dmgame.com/static/upload/game/65a7365985d61.webp" },
    { key: "Nioh2", name: "仁王2", sourceName: "Nioh 2", steamAppId: 1325200, cover: "https://assets-mod.3dmgame.com/static/upload/game/6041c647d7a35.png" },
    { key: "Nioh3", name: "仁王3", sourceName: "Nioh 3", steamAppId: 3681010, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_699ec8ac99e3b.png" },
    { key: "LikeADragon8", name: "如龙8", sourceName: "LikeADragon8", steamAppId: 2072450, cover: "https://assets-mod.3dmgame.com/static/upload/game/65b9e51412790.webp" },
    { key: "Cyberpunk2077", name: "赛博朋克2077", sourceName: "Cyberpunk 2077", steamAppId: 1091500, cover: "https://assets-mod.3dmgame.com/static/upload/game/195.png" },
    { key: "DeadRisingDeluxeRemaster", name: "丧尸围城豪华复刻版", sourceName: "Dead Rising Deluxe Remaster", steamAppId: 2527390, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202410/MOD67077f9f042f5.webp@webp" },
    { key: "SonsOfTheForest", name: "森林之子", sourceName: "Sons Of The Forest", steamAppId: 1326470, cover: "https://assets-mod.3dmgame.com/static/upload/game/63fc08e3ef48b.webp" },
    { key: "TheLostVillage", name: "山门与幻境", sourceName: "The Lost Village", steamAppId: 1963040, cover: "https://assets-mod.3dmgame.com/static/upload/game/6629bb7235d50.webp" },
    { key: "OblivionRemastered", name: "上古卷轴4：湮灭 重制版", sourceName: "Oblivion Remastered", steamAppId: 2623190, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_68084078343d1.jpg" },
    { key: "SkyrimSE", name: "上古卷轴5: 重制版", sourceName: "Skyrim Special Edition", steamAppId: 489830, cover: "https://assets-mod.3dmgame.com/static/upload/game/2.jpg" },
    { key: "Subnautica", name: "深海迷航", sourceName: "Subnautica", steamAppId: 264710, cover: "https://assets-mod.3dmgame.com/static/upload/game/105a.jpg" },
    { key: "Divinityos2", name: "神界: 原罪2", sourceName: "Divinity Original Sin 2", steamAppId: 435150, cover: "https://assets-mod.3dmgame.com/static/upload/game/34.jpg" },
    { key: "RE2Remake", name: "生化危机2: 重制版", sourceName: "Resident Evil 2", steamAppId: 883710, cover: "https://assets-mod.3dmgame.com/static/upload/game/180.png" },
    { key: "RE3Remake", name: "生化危机3重制版", sourceName: "Resident Evil 3", steamAppId: 952060, cover: "https://assets-mod.3dmgame.com/static/upload/game/224.png" },
    { key: "RE4Remake", name: "生化危机4 重制版", sourceName: "RE4Remake", steamAppId: 2050650, cover: "https://assets-mod.3dmgame.com/static/upload/game/63e310bf62591.webp" },
    { key: "ResidentEvilVillage", name: "生化危机8: 村庄", sourceName: "Resident Evil Village", steamAppId: 1196590, cover: "https://assets-mod.3dmgame.com/static/upload/game/6095126f96a6d.png" },
    { key: "ResidentEvilRequiem", name: "生化危机9 安魂曲", sourceName: "Resident Evil Requiem", steamAppId: 3764200, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_69a0f03164da1.png" },
    { key: "SiFu", name: "师父", sourceName: "SiFu", steamAppId: 2138710, cover: "https://assets-mod.3dmgame.com/static/upload/game/62207195e18a2.png" },
    { key: "CrusaderKings3", name: "十字军之王3", sourceName: "Crusader Kings 3", steamAppId: 1158310, cover: "https://assets-mod.3dmgame.com/static/upload/game/236.png" },
    { key: "CodeVein", name: "噬血代码", sourceName: "CODE VEIN", steamAppId: 678960, cover: "https://assets-mod.3dmgame.com/static/upload/game/207.png" },
    { key: "TwoPointCampus", name: "双点校园", sourceName: "Two Point Campus", steamAppId: 1649080, cover: "https://assets-mod.3dmgame.com/static/upload/game/65a74761bb3fe.webp" },
    { key: "DeadOrAlive6", name: "死或生 6", sourceName: "Dead or Alive 6", steamAppId: 838380, cover: "https://assets-mod.3dmgame.com/static/upload/game/182.jpg" },
    { key: "Flintlock", name: "燧石枪：黎明之围", sourceName: "Flintlock The Siege of Dawn", steamAppId: 1832040, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202407/MOD669a223b01b15.webp@webp" },
    { key: "TheScrollOfTaiwu", name: "太吾绘卷", sourceName: "The Scroll Of Taiwu", steamAppId: 838350, cover: "https://assets-mod.3dmgame.com/static/upload/game/167.png" },
    { key: "Terraria", name: "泰拉瑞亚", sourceName: "Terraria", steamAppId: 105600, cover: "https://assets-mod.3dmgame.com/static/upload/game/64cc631c336ce.webp" },
    { key: "Titanfall2", name: "泰坦陨落2", sourceName: "Titanfall 2", steamAppId: 1237970, cover: "https://assets-mod.3dmgame.com/static/upload/game/65a9d3b2453ae.webp" },
    { key: "Duckov", name: "逃离鸭科夫", sourceName: "Escape from Duckov", steamAppId: 3167020, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_68f704683991c.png" },
    { key: "KingdomComeDeliverance2", name: "天国: 拯救2", sourceName: "Kingdom Come Deliverance 2", steamAppId: 1771300, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202502/MOD67a1ffc3c7198.jpg@webp" },
    { key: "KingdomComeDeliverance", name: "天国拯救", sourceName: "Kingdom Come Deliverance", steamAppId: 379430, cover: "https://assets-mod.3dmgame.com/static/upload/game/155.jpg" },
    { key: "Tekken8", name: "铁拳8", sourceName: "Tekken 8", steamAppId: 1778820, cover: "https://assets-mod.3dmgame.com/static/upload/game/65b9e69f3b61b.webp" },
    { key: "JaggedAlliance3", name: "铁血联盟3", sourceName: "Jagged Alliance 3", steamAppId: 1084160, cover: "https://assets-mod.3dmgame.com/static/upload/game/64be23bb84fe3.webp" },
    { key: "GranblueFantasyRelink", name: "蔚蓝幻想 Relink", sourceName: "Granblue Fantasy Relink", steamAppId: 881020, cover: "https://assets-mod.3dmgame.com/static/upload/game/65bb62a24e92f.webp" },
    { key: "CivilizationVI", name: "文明6", sourceName: "Sid Meier's Civilization VI", steamAppId: 289070, cover: "https://assets-mod.3dmgame.com/static/upload/game/5.jpg" },
    { key: "TheWitcher3", name: "巫师3: 狂猎", sourceName: "The Witcher 3", steamAppId: 292030, cover: "https://assets-mod.3dmgame.com/static/upload/game/4a.jpg" },
    { key: "NoMansSky", name: "无人深空", sourceName: "No Man's Sky", steamAppId: 275850, cover: "https://assets-mod.3dmgame.com/static/upload/game/24.jpg" },
    { key: "WarriorsOrochi4", name: "无双大蛇3", sourceName: "Warriors Orochi 4", steamAppId: 831560, cover: "https://assets-mod.3dmgame.com/static/upload/game/168.jpg" },
    { key: "Borderlands3", name: "无主之地3", sourceName: "Borderlands 3", steamAppId: 397540, cover: "https://assets-mod.3dmgame.com/static/upload/game/188_1.png" },
    { key: "Borderlands4", name: "无主之地4", sourceName: "Borderlands 4", steamAppId: 1285190, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_68c3711a6f87b.jpg" },
    { key: "CivilizationVII", name: "席德·梅尔的文明7", sourceName: "Sid Meier's Civilization VII", steamAppId: 1295660, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_681b310c641ef.jpg" },
    { key: "GTA5Enhanced", name: "侠盗猎车手5 增强版 (GTA5)", sourceName: "Grand Theft Auto V Enhanced", steamAppId: 3240220, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_692fc8cd5ea06.png" },
    { key: "GTA5", name: "侠盗猎车手系列 (GTA)", sourceName: "Grand Theft Auto V", steamAppId: 271590, cover: "https://assets-mod.3dmgame.com/static/upload/game/616cd448533b9.png" },
    { key: "NextJianghu2", name: "下一站江湖2", sourceName: "Next Jianghu 2", steamAppId: 1606180, cover: "https://assets-mod.3dmgame.com/static/upload/game/6629b6eff3688.webp" },
    { key: "Pal7", name: "仙剑奇侠传7", sourceName: "Pal7", steamAppId: 1543030, cover: "https://assets-mod.3dmgame.com/static/upload/game/6256729d72a41.png" },
    { key: "DyingLight2", name: "消逝的光芒2", sourceName: "Dying Light 2", steamAppId: 534380, cover: "https://assets-mod.3dmgame.com/static/upload/game/61dbf5a660a03.png" },
    { key: "Starfield", name: "星空", sourceName: "Starfield", steamAppId: 1716740, cover: "https://assets-mod.3dmgame.com/static/upload/game/64db454e9f5c4.webp" },
    { key: "StardewValley", name: "星露谷物语", sourceName: "Stardew Valley", steamAppId: 413150, cover: "https://assets-mod.3dmgame.com/static/upload/game/10.jpg" },
    { key: "VRising", name: "夜族崛起", sourceName: "VRising", steamAppId: 1604030, cover: "https://assets-mod.3dmgame.com/static/upload/game/632f15e51ee2c.png" },
    { key: "Shapez2", name: "异形工厂 2", sourceName: "Shapez 2", steamAppId: 2162800, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202408/MOD66bf055eb2ba5.webp@webp" },
    { key: "WanderingSword", name: "逸剑风云决", sourceName: "Wandering Sword", steamAppId: 1876890, cover: "https://assets-mod.3dmgame.com/static/upload/game/656d920e5f559.webp" },
    { key: "Valheim", name: "英灵神殿", sourceName: "Valheim", steamAppId: 892970, cover: "https://assets-mod.3dmgame.com/static/upload/game/65f1415124b36.webp" },
    { key: "LegendOfHeros", name: "英雄立志传 三国志", sourceName: "Legend of Heroes Three Kingdoms", steamAppId: 3020510, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_67eca42846bf0.jpg" },
    { key: "DQIIIHD2DRemake", name: "勇者斗恶龙III HD-2D Remake", sourceName: "DQIIIHD2DRemake", steamAppId: 2701660, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202412/MOD675a59d27912a.png@webp" },
    { key: "Xcom2", name: "幽浮2", sourceName: "XCOM2", steamAppId: 268500, cover: "https://assets-mod.3dmgame.com/static/upload/game/38.jpg" },
    { key: "RiskofRain2", name: "雨中冒险2", sourceName: "Risk of Rain 2", steamAppId: 632360, cover: "https://assets-mod.3dmgame.com/static/upload/game/607926e04c16a.png" },
    { key: "Genshin Impact", name: "原神", sourceName: "Genshin Impact", steamAppId: 0, cover: "https://assets-mod.3dmgame.com/static/upload/game/66da7e920f43e.webp" },
    { key: "AtomicHeart", name: "原子之心", sourceName: "Atomic Heart", steamAppId: 668580, cover: "https://assets-mod.3dmgame.com/static/upload/game/63f5846644d4e.webp" },
    { key: "Expeditions", name: "远征: 泥泞奔驰游戏", sourceName: "Expeditions A MudRunner Game", steamAppId: 2477340, cover: "https://assets-mod.3dmgame.com/static/upload/game/6670007e442e8.webp" },
    { key: "SpaceMarine2", name: "战锤40K: 星际战士2", sourceName: "Warhammer 40000 Space Marine 2", steamAppId: 2183900, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202410/MOD6707728ca7d89.webp@webp" },
    { key: "Just Cause 3", name: "正当防卫3", sourceName: "Just Cause 3", steamAppId: 225540, cover: "https://assets-mod.3dmgame.com/static/upload/game/50.jpg" },
    { key: "Sekiro", name: "只狼", sourceName: "Sekiro", steamAppId: 814380, cover: "https://assets-mod.3dmgame.com/static/upload/game/185.png" },
    { key: "LethalCompany", name: "致命公司", sourceName: "Lethal Company", steamAppId: 1966720, cover: "https://assets-mod.3dmgame.com/static/upload/game/65a0f0fb13a40.webp" },
    { key: "ManorLords", name: "庄园领主", sourceName: "Manor Lords", steamAppId: 1363080, cover: "https://assets-mod.3dmgame.com/static/upload/game/662db2a8b4521.webp" },
    { key: "ArmoredCore6", name: "装甲核心6", sourceName: "Armored Core 6", steamAppId: 1888160, cover: "https://assets-mod.3dmgame.com/static/upload/game/64e5a555a4360.webp" },
    { key: "LastUs2", name: "最后生还者2", sourceName: "The Last of Us Part 2", steamAppId: 2531310, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_67fdc9247cc4b.jpg" },
    { key: "FF7Rebirth", name: "最终幻想7 重生", sourceName: "FINAL FANTASY VII REBIRTH", steamAppId: 2909400, cover: "https://assets-mod.3dmgame.com/static/upload/logo/croppedImg_683582d5e4a77.jpg" },
    { key: "FF7RE", name: "最终幻想7 重制版", sourceName: "FINAL FANTASY VII REMAKE", steamAppId: 1462040, cover: "https://assets-mod.3dmgame.com/static/upload/game/61c027ed1cbc1.png" },
    { key: "GTASADE", name: "GTA 圣安地列斯 最终版", sourceName: "GTA San Andreas Definitive Edition", steamAppId: 1547000, cover: "/imgs/gtasade_logo.jpg" },
    { key: "InZOI", name: "inZOI", sourceName: "inZOI", steamAppId: 2456740, cover: "https://assets-mod.3dmgame.com/static/upload/mod/202503/MOD67c7ff0ec9f40.webp@webp" },
    { key: "JumpForce", name: "Jump大乱斗", sourceName: "JUMP FORCE", steamAppId: 816020, cover: "https://assets-mod.3dmgame.com/static/upload/game/181.jpg" },
    { key: "X4Foundations", name: "X4 基石", sourceName: "X4 Foundations", steamAppId: 392160, cover: "https://assets-mod.3dmgame.com/static/upload/game/178.png" },
].sort((a, b) => a.name.localeCompare(b.name, "zh-Hans-CN"));

export const supportedGamesCount = supportedGames.length;
