name: 反馈Bug
description: 向我们反馈一个BUg
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              如果在使用的过程中遇到了Bug,请反馈给我!
    - type: input
      id: version
      attributes:
          label: 管理器版本
          description: 你使用的管理器是什么版本的? (在设置里面查看)
          placeholder: ex. 1.26.0
      validations:
          required: false
    - type: textarea
      id: describe
      attributes:
          label: 描述
          description: 将你遇到的Bug描述出来?
          placeholder: 尽量具体的进行描述,以方便我们进行处理!
          value: "A bug happened!"
      validations:
          required: true
    - type: textarea
      id: recurrent
      attributes:
          label: 如何触发
          description: 你是如何触发这个Bug的, 将步骤描述出来?
          placeholder: 将步骤进行尽可能的详细描述出来!
          value: "A bug happened!"
      validations:
          required: true
    - type: dropdown
      id: system
      attributes:
          label: 操作系统
          description: 你使用的是什么系统?
          options:
              - Windows 7
              - Windows 10
              - Windows 11
              - 其他
          default: 0
      validations:
          required: true
    - type: input
      id: system-other
      attributes:
          label: 其他?
          description: "如果你使用的是其他系统,请写出来"
          placeholder: ""
