/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/ui/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./components/ui/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./components/ui/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./components/ui/accordion/AccordionTrigger.vue')['default']
    Badge: typeof import('./components/ui/badge/Badge.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardAction: typeof import('./components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    DocsLayout: typeof import('./components/DocsLayout.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./components/ui/switch/Switch.vue')['default']
  }
}
