/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/add-new-game': RouteRecordInfo<
      '/add-new-game',
      '/add-new-game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/': RouteRecordInfo<
      '/docs/',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/[...slug]': RouteRecordInfo<
      '/docs/[...slug]',
      '/docs/:slug(.*)',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/download': RouteRecordInfo<
      '/download',
      '/download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games': RouteRecordInfo<
      '/games',
      '/games',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/add-new-game.vue': {
      routes:
        | '/add-new-game'
      views:
        | never
    }
    'src/pages/docs/index.vue': {
      routes:
        | '/docs/'
      views:
        | never
    }
    'src/pages/docs/[...slug].vue': {
      routes:
        | '/docs/[...slug]'
      views:
        | never
    }
    'src/pages/download.vue': {
      routes:
        | '/download'
      views:
        | never
    }
    'src/pages/games.vue': {
      routes:
        | '/games'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
