/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/law/': RouteRecordInfo<
      '/law/',
      '/law',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/law/auth': RouteRecordInfo<
      '/law/auth',
      '/law/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/law/chat': RouteRecordInfo<
      '/law/chat',
      '/law/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/law/document': RouteRecordInfo<
      '/law/document',
      '/law/document',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/law/orders': RouteRecordInfo<
      '/law/orders',
      '/law/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/law/profile': RouteRecordInfo<
      '/law/profile',
      '/law/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/law/recharge': RouteRecordInfo<
      '/law/recharge',
      '/law/recharge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/law/settings': RouteRecordInfo<
      '/law/settings',
      '/law/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/law/index.vue': {
      routes:
        | '/law/'
      views:
        | never
    }
    'src/pages/law/auth.vue': {
      routes:
        | '/law/auth'
      views:
        | never
    }
    'src/pages/law/chat.vue': {
      routes:
        | '/law/chat'
      views:
        | never
    }
    'src/pages/law/document.vue': {
      routes:
        | '/law/document'
      views:
        | never
    }
    'src/pages/law/orders.vue': {
      routes:
        | '/law/orders'
      views:
        | never
    }
    'src/pages/law/profile.vue': {
      routes:
        | '/law/profile'
      views:
        | never
    }
    'src/pages/law/recharge.vue': {
      routes:
        | '/law/recharge'
      views:
        | never
    }
    'src/pages/law/settings.vue': {
      routes:
        | '/law/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
